# -*- coding: utf-8 -*-
"""Ishwari_Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPIx08boAkTdRkso9uREUxiG0ikVjlFz
"""

import os
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#Loading and exploring the dataset
df=pd.read_csv('/content/Indian_Traffic_Violations.csv')
df.head() #showing first five rows.

#Fine Paid vs Vehicle Type
fine_data = df.groupby('Vehicle_Type')['Fine_Amount'].sum()# Group total fine paid per vehicle type
plt.figure(figsize=(8, 8))
plt.pie(
    fine_data.values,
    labels=fine_data.index,
    autopct='%1.1f%%',
    startangle=90
)
plt.title("Fine Paid vs Vehicle Type", fontsize=14)
plt.axis('equal')
plt.show()

# Average fine per location
fine_location = df.groupby('Location')['Fine_Amount'].mean().reset_index()

plt.figure(figsize=(10,5))      #set the size of the graph width and height.
plt.plot(                       #plot the line graph,x-axis location,y-axis Fine Amount.
    fine_location['Location'],
    fine_location['Fine_Amount'],
    marker='o'#shows a dot at each point,making each locations value visible.
)
plt.title("Average Fine Amount vs Location")#add title and label for clearity.
plt.xlabel("Location")
plt.ylabel("Average Fine Amount")
plt.xticks(rotation=45)#Rotate location names to avoid overlap.
plt.grid(True) #Add gridline for easy comparison.
plt.tight_layout()#Adjust spacing automatically.adjust layout,labels and title do not overlap.
plt.show()  #Display graph.